#+TITLE: Notes with Orgmode and Github

* What to do with Notes 

For simple notes Apple Notes has the virtue of being always available.

Other apps like OneNote, [[https://evernote.com][Evernote]], [[https://www.gingerlabs.com][Notability]] have some serious drawbacks:

- Cost money often as a subscription model and the company (other than Microsoft) is liable of going out of business
  at any time.
- Proprietary file formats 
- Challenged by text formatting, either very messy or non-existent

* Editor - Emacs



* Markdown

So lately I have been using [Markdown](https://www.markdownguide.org) for keeping notes. There are some Markdown
editors available on mobile devices, looks very nice but I use [1Writer](https://1writerapp.com) which does not
require a subscription. The apps can access Markdown files stored on the cloud, such as iCloud Drive or Dropbox.

One last problem is that while these apps offer a "preview" of the notes in HTML, they cannot share notes in HTML.

* Emacs and Org-mode

[[https://orgmode.org][Org-mode]]

* Github

Then I found out that I can use Github to keep notes in Markdown, edit them in either Emacs or 1Writer, and make the
resulted HTML available as web pages. This is very easy although it is surprisingly hard to find a clear instruction.

- Register a free account on Github.
- Start a new repository, name it *username.github.io* which will be the URL for the website.
  - There is a choice of making the repository public or private. If the former, the URL is visible by the public,
    although only "collaborators" can edit the pages.
  - One can also pick a theme for the rendered HTML pages.
- Select 'yes' to automatically generate a ~README.md~ file, which will be the starting page.
- Check out the repository to the computer. Note that as a public repository, a password is not required to check out
  a repository, only when checking in.

#+begin_src shell
  % git clone https://github.com/username/username.github.io
#+end_src

- Now one can edit the Markdown files either on computer and push the edits to the server; or edit the files directly
  in a web browser.
- There are two URLs to keep in mind, ~github.com/username/username.github.io~ shows the github repository for
  editing, and ~username.github.io~ which shows the HTML files. Note that the HTML files are statically generated by
  [[https://jekyllrb.com][Jekyll]] and changes to the Markdown files may take some time to show up in the HTML.
- Github uses [[https://github.github.com/gfm/][Github Flavored Markdown]]. From the ~README.md~, relative links to other pages can be inserted via
  ~[page name](filename.md)~.
  

